# Minima theme configuration
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# valid social icon names can be found at https://fontawesome.com/search?ic=brands

minima:
  skin: auto
  hide_site_feed_link: true
  show_excerpts: true
  social_links:
    - title: "Source Code"
      icon: git-alt
      url: "https://github.com/blwatkins/sketches"
    - title: "GitHub Pages"
      icon: square-github
      url: "https://blwatkins.github.io/"
    - title: GitHub
      icon: github
      url: "https://github.com/blwatkins"
    - title: YouTube
      icon: youtube
      url: "https://www.youtube.com/channel/UCeJ-huUU2AWP0z4-HWr1BXQ"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/brittni-watkins/"
  nav_pages:
    - index.md

title: "Sketches, by Brittni Watkins"
description: "Generative art sketches built using p5.js with shared utility classes for creative coding."
show_downloads: true

exclude:
  - .ruby-version
  - Gemfile
  - Gemfile.lock
